refactor(config): move transport item to cijoe
refenv/cijoe pull request #64
Opened 2024-06-04 13:19 UTC by NaddiNadja

Move the top-level item `transport` under top-level item `cijoe` to match with all other top level identifiers in the configuration-file.

Closes #60

2024-06-11 10:19 UTC, safl reviewed
This probably also need to adjust some ``.config`` files? E.g. the default configs, and possibly some documentation as well?

2024-06-11 10:29 UTC, safl requested changes
This probably also need to adjust some ``.toml`` files such as the default configs, and possibly some documentation as well. For example:

* ``src/cijoe/core/configs/transport-ssh.toml``

Let's integrate the merge of the packages https://github.com/refenv/cijoe/pull/63 and then this one after, then there are probably more ``.toml`` files to fix and then it can be done in a single commit.

2024-06-12 07:16 UTC, NaddiNadja commented
I did a search for `transport` in the repository, and it looks like only `docs/source/usage/index.rst` and `src/cijoe/core/configs/transport-ssh.toml` needed to be updated, but let me know if you think I'm missing something. :)

2024-06-12 07:32 UTC, safl commented
Sounds good, now with https://github.com/refenv/cijoe/pull/63 merged, after you rebase, then there might some additional example-configs to adjust?

2024-06-12 07:41 UTC, safl approved these changes

2024-06-12 07:41 UTC, merged