Cleanup
refenv/cijoe pull request #86
Opened 2024-10-11 13:03 UTC by safl

This is a collection of **cleanup** in the form of improvements to documentation, removal of deprecations, and misc. fixes.

2024-10-14 11:18 UTC, NaddiNadja requested changes
only some comments on language - pick and choose what you think is appropriate :)

2024-10-14 11:18 UTC, NaddiNadja commented on docs/source/prerequisites/index.rst
> +**initiator** and **target** systems cover.
Maybe just "The diagram below illustrates what the **initiator** and **target** systems cover." to keep the language a bit more formal?

2024-10-14 11:18 UTC, NaddiNadja commented on docs/source/prerequisites/index.rst
> +invoked, and the **cijoe** scripts are executing, requiring :python:`Python
no comma after "invoked" and maybe change to "and the **cijoe** scripts are being executed" instead of "are executing"

2024-10-14 11:18 UTC, NaddiNadja commented on docs/source/prerequisites/index.rst
> +are transferred using **scp**, both of which must be properly set up. As
maybe "installed and configured" instead of "set up"?

2024-10-14 11:18 UTC, NaddiNadja commented on docs/source/prerequisites/index.rst
> +    **initiator** side where you **cijoe** script is executing. Therefore, keep
"your" instead of "you"

2024-10-14 11:18 UTC, NaddiNadja commented on docs/source/prerequisites/index.rst
> +production-environment facing the public internet. However, do keep in mind that
no hyphen in "production environment"

2024-10-14 11:18 UTC, NaddiNadja commented on docs/source/prerequisites/index.rst
> +There are also scenarious, where you want to execute using a **non-root** user.
"scenarios" instead of "scenarious"

2024-10-14 11:18 UTC, NaddiNadja commented on docs/emit.py
> +include  a Python module, packaged within a Python package. Including a Python module is
idk if it matters, but there's a double space between "include" and "a"

2024-10-14 13:38 UTC, karlowich requested changes
Couple of nitpicks

2024-10-14 13:38 UTC, karlowich commented on docs/source/prerequisites/index.rst
> +    do so by writing **cijoe** script that does the installation of the tool,
> writing \*\*cijoe\*\*

`writing a **cijoe**`

2024-10-14 13:38 UTC, karlowich commented on docs/source/prerequisites/index.rst
> +    transfer with ``cijoe.put()`` and ``cijoe.run()`` to invoke installation. Or
> transfer with

`transfer it with`

2024-10-14 13:38 UTC, karlowich commented on docs/source/prerequisites/index.rst
> +**expect-like** functionality. By bypassing the password prompt, you simplify
What do you mean by "expect-like"?

2024-10-15 07:44 UTC, safl commented on docs/source/prerequisites/index.rst
> +**expect-like** functionality. By bypassing the password prompt, you simplify
I've added a link.

2024-10-15 07:49 UTC, safl commented
Thanks @NaddiNadja and @karlowich for you input!

2024-10-15 09:18 UTC, NaddiNadja approved these changes
lgtm :)

2024-10-15 14:12 UTC, merged